[package]
name = "kokoro-plugin-tiny-http-event"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kokoro = { version = "0.0.6", path = "../../kokoro" }
tiny_http = "0.12.0"
